//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2kvalikSemenova.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuitService
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public byte[] ImageBinary { get; set; }
        public Nullable<int> SuitType_Id { get; set; }
    
        public virtual SuitType SuitType { get; set; }
    }
}
